select * from abilities;
select * from base_stats; 
select * from heroes; 
select * from match_description; 
select * from match_performance; 
select * from matches; 
select * from participating_teams; 
select * from player_characters;
select * from players;
select * from roles;
select * from teams;
select * from teams_player;
select * from teams_teams; 
select * from tournament_type;

delete from abilities;
delete from base_stats; 
delete from heroes; 
delete from match_description; 
delete from match_performance; 
delete from matches; 
delete from participating_teams; 
delete from player_characters;
delete from players;
delete from roles;
delete from teams;
delete from teams_player;
delete from teams_teams; 
delete from tournament_type;