table_names = ["players",
               "tournament_type",
               "matches",
               "participating_teams",
               "heroes",
               "base_stats",
               "abilities",
               "player_characters",
               "match_description",
               "match_performance",
               "teams",
               "teams_teams",
               "roles",
               "teams_player"]

attrs = [
    [('steam_name', 1),
     ('steam_id', 1),
        ('name', 1),
        ('country_of_origin', 1),
        ('date_of_birth', 1),
        ('signature_hero', 1),
        ('playtime', 0),
        ('status', 1)],
    [('tournament', 1), ('type', 1)],
    [('match_id', 1),
        ('winner', 1),
        ('mvp', 1),
        ('loser', 1),
        ('tournament', 1),
        ('duration', 0)],
    [('match_id', 1), ('team_1', 1), ('team_2', 1)],
    [('name', 1), ('faction', 1), ('primary_attribute', 1), ('lore', 1)],
    [('hero_name', 1),
        ('turn_rate', 0),
        ('hp_regen', 0),
        ('mana_regen', 0),
        ('sight_range', 0),
        ('attack_range', 0),
        ('missile_range', 0),
        ('attack_duration', 0),
        ('cast_duration', 0),
        ('magic_resist', 0),
        ('attack_speed', 0),
        ('attack_time', 0)],
    [('hero_name', 1),
        ('ability_name', 1),
        ('manacost', 0),
        ('cooldown', 0),
        ('description', 1)],
    [('hero_name', 1),
        ('steam_id', 1),
        ('wins', 0),
        ('matches_played', 0),
        ('win_rate', 0)],
    [('match_id', 1),
        ('steam_id', 1),
        ('hero_name', 1),
        ('team_1', 1),
        ('team_2', 1)],
    [('match_id', 1),
        ('steam_id', 1),
        ('kills', 0),
        ('deaths', 0),
        ('assists', 0)],
    [('team_name', 1), ('player', 1), ('losses', 0), ('wins', 0)],
    [('team_1', 1),
        ('team_2', 1),
        ('player_11', 1),
        ('player_21', 1),
        ('losses', 0),
        ('wins', 0)],
    [('steam_id', 1), ('roles', 1)],
    [('player_id', 1), ('team_name', 1), ('join_date', 1), ('participation', 0)]
]
